###############################
#           PAYDAY            #
###############################

# Boring MySQL Shit

MySQL:
  Enable: false
  Address: localhost
  Port: 3306
  Database: payday
  Username: root
  Password: pass
  
# Arena Settings

Map-Name: Test
Mission-Objective: Objective
Payday-Lobby-Server: payday
Loot-Needed: 4
Players-Needed: 4